// <auto-generated />
using System;
using System.Text.Json;
using HomeLabGymApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeLabGymApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeLabGymApi.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<JsonDocument>("AdditionalSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_settings");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exercise_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseType")
                        .HasDatabaseName("idx_exercise_type");

                    b.ToTable("exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fb65bec-fb9e-41c8-82c4-66a4ab15148b"),
                            Category = "shoulders",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2544), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Overhead push press with legs drive",
                            ExerciseType = "Strength",
                            Name = "Push Press",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2545), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("6ed4004d-7b48-4542-a892-2c20d99c6b96"),
                            Category = "chest",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2560), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Horizontal pressing movement",
                            ExerciseType = "Strength",
                            Name = "Bench Press",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2560), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("969dc17e-ca07-4c1e-b482-12167ba2a015"),
                            Category = "legs",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2574), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Barbell back squat",
                            ExerciseType = "Strength",
                            Name = "Back Squat",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 11, 30, 19, 5, 46, 465, DateTimeKind.Unspecified).AddTicks(2574), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HomeLabGymApi.Models.ExerciseLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("exercise_links", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.ExerciseTag", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("ExerciseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("exercise_tags", (string)null);

                    b.HasData(
                        new
                        {
                            ExerciseId = new Guid("7fb65bec-fb9e-41c8-82c4-66a4ab15148b"),
                            TagId = new Guid("9c56ffd6-3aed-4420-9dc5-70e5b6db414e")
                        },
                        new
                        {
                            ExerciseId = new Guid("6ed4004d-7b48-4542-a892-2c20d99c6b96"),
                            TagId = new Guid("9c56ffd6-3aed-4420-9dc5-70e5b6db414e")
                        },
                        new
                        {
                            ExerciseId = new Guid("969dc17e-ca07-4c1e-b482-12167ba2a015"),
                            TagId = new Guid("0372d9c0-8b12-43b3-ac63-b5269fb10521")
                        });
                });

            modelBuilder.Entity("HomeLabGymApi.Models.SessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<Guid>("WorkoutSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("session_exercises", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_tag_name_unique");

                    b.ToTable("tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c56ffd6-3aed-4420-9dc5-70e5b6db414e"),
                            Name = "push"
                        },
                        new
                        {
                            Id = new Guid("45b9aa4c-82aa-4eb5-83e0-7d670d6cf865"),
                            Name = "pull"
                        },
                        new
                        {
                            Id = new Guid("0372d9c0-8b12-43b3-ac63-b5269fb10521"),
                            Name = "legs"
                        });
                });

            modelBuilder.Entity("HomeLabGymApi.Models.TemplateExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<int>("OrderIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_index");

                    b.Property<Guid>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("template_exercises", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.TemplateSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<JsonDocument>("Metrics")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.Property<Guid>("TemplateExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateExerciseId");

                    b.ToTable("template_sets", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("SessionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("session_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("workout_template_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionDate")
                        .HasDatabaseName("idx_workout_session_date");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("workout_sessions", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("completed");

                    b.Property<JsonDocument>("Metrics")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("SessionExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_exercise_id");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer")
                        .HasColumnName("set_number");

                    b.HasKey("Id");

                    b.HasIndex("SessionExerciseId");

                    b.ToTable("workout_sets", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("workout_templates", (string)null);
                });

            modelBuilder.Entity("HomeLabGymApi.Models.ExerciseLink", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.Exercise", "Exercise")
                        .WithMany("Links")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.ExerciseTag", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.Exercise", "Exercise")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeLabGymApi.Models.Tag", "Tag")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.SessionExercise", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeLabGymApi.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.TemplateExercise", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.Exercise", "Exercise")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeLabGymApi.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.TemplateSet", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.TemplateExercise", "TemplateExercise")
                        .WithMany("TemplateSets")
                        .HasForeignKey("TemplateExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateExercise");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutSession", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutSet", b =>
                {
                    b.HasOne("HomeLabGymApi.Models.SessionExercise", "SessionExercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("SessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseTags");

                    b.Navigation("Links");

                    b.Navigation("SessionExercises");

                    b.Navigation("TemplateExercises");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.SessionExercise", b =>
                {
                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.Tag", b =>
                {
                    b.Navigation("ExerciseTags");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.TemplateExercise", b =>
                {
                    b.Navigation("TemplateSets");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutSession", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("HomeLabGymApi.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
